import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import { DollarSign, FileText, TrendingUp, Clock, Calendar, AlertCircle, Download, Loader2 } from 'lucide-react';
import { ScrollReveal } from '@/components/ui/ScrollReveal';
import { useEarnings } from '@/hooks/useEarnings';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

export default function Earnings() {
    const { user } = useAuth();
    const { commissions, payslips, stats, loading } = useEarnings();

    // Helper to format currency
    const formatCurrency = (amount: number) => {
        return new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: 'USD',
            maximumFractionDigits: 0,
        }).format(amount);
    };

    // Generate PDF for download
    const handleDownloadReport = () => {
        try {
            const doc = new jsPDF();
            const dateStr = format(new Date(), 'MMM dd, yyyy');

            // --- Header Section ---
            doc.setFontSize(22);
            doc.setTextColor(40, 40, 40);
            doc.setFont("helvetica", "bold");
            doc.text("Nexus ERP", 14, 20);

            doc.setFontSize(14);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(100, 100, 100);
            doc.text("Earnings & Commissions Report", 14, 28);

            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text(`Date: ${dateStr}`, 14, 35);
            doc.text(`Report ID: EARN-${Math.floor(Math.random() * 10000)}`, 14, 40);

            doc.setDrawColor(200, 200, 200);
            doc.line(14, 45, 196, 45);

            // --- Summary Section ---
            doc.setFontSize(12);
            doc.setTextColor(40, 40, 40);
            doc.setFont("helvetica", "bold");
            doc.text("Financial Summary", 14, 55);

            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text(`Total Earnings (YTD): ${formatCurrency(stats.totalEarnings)}`, 14, 62);
            doc.text(`Commissions (Performance): ${formatCurrency(stats.commissionEarnedYTD)}`, 14, 67);
            doc.text(`Pending Payouts: ${formatCurrency(stats.commissionPending)}`, 14, 72);

            // --- Table Section ---
            const head = [['Date', 'Deal Name', 'Status', 'Amount']];
            const body = commissions.map(item => [
                format(new Date(item.date), 'MMM dd, yyyy'),
                item.deal_name,
                item.status.toUpperCase(),
                formatCurrency(item.amount)
            ]);

            autoTable(doc, {
                startY: 80,
                head: head,
                body: body,
                theme: 'grid',
                headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' }, // Indigo-600 match
                styles: { fontSize: 10, cellPadding: 3 },
                alternateRowStyles: { fillColor: [248, 250, 252] },
            });

            // --- Footer Section ---
            const pageCount = (doc as any).internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150, 150, 150);
                const pageSize = doc.internal.pageSize;
                const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
                doc.text(`Generated by Nexus ERP System - Confidential`, 14, pageHeight - 10);
                doc.text(`Page ${i} of ${pageCount}`, pageSize.width - 25, pageHeight - 10);
            }

            doc.save(`Nexus_Earnings_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);

        } catch (error) {
            console.error("PDF Generation failed:", error);
        }
    };

    // Generate Payslip PDF
    const handleDownloadPayslip = (slip: any) => {
        try {
            const doc = new jsPDF();
            const dateStr = format(new Date(), 'MMM dd, yyyy');
            const monthStr = new Date(slip.month).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

            // --- Header ---
            doc.setFontSize(22);
            doc.setTextColor(40, 40, 40);
            doc.setFont("helvetica", "bold");
            doc.text("Nexus ERP", 14, 20);

            doc.setFontSize(14);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(100, 100, 100);
            doc.text("Payslip / Salary Statement", 14, 28);

            doc.setDrawColor(200, 200, 200);
            doc.line(14, 35, 196, 35);

            // --- Employee & Period Details ---
            doc.setFontSize(10);
            doc.setTextColor(40, 40, 40);

            // Use metadata or fallbacks
            doc.text(`Employee Name: ${user?.user_metadata?.full_name || user?.email || 'N/A'}`, 14, 45);
            doc.text(`Employee ID: ${user?.id?.slice(0, 8).toUpperCase() || 'N/A'}`, 14, 50);
            doc.text(`Pay Period: ${monthStr}`, 14, 55);

            doc.text(`Generated Date: ${dateStr}`, 140, 45);
            doc.text(`Status: ${slip.status?.toUpperCase() || 'PROCESSED'}`, 140, 50);

            // --- Earnings Table ---
            const head = [['Description', 'Amount']];
            const body = [
                ['Base Salary', formatCurrency(slip.base_amount)],
                ['Commissions & Bonuses', formatCurrency(slip.commission_amount)],
                ['Total Deductions', formatCurrency(0)], // Placeholder if no deduction data
            ];

            autoTable(doc, {
                startY: 65,
                head: head,
                body: body,
                theme: 'grid',
                headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
                styles: { fontSize: 10, cellPadding: 3 },
                columnStyles: {
                    0: { cellWidth: 120 },
                    1: { cellWidth: 50, halign: 'right' },
                }
            });

            // --- Net Pay Section ---
            const finalY = (doc as any).lastAutoTable.finalY + 10;

            doc.setFontSize(11);
            doc.setFont("helvetica", "bold");
            doc.text("Total Net Pay:", 130, finalY);
            doc.setFontSize(12);
            doc.setTextColor(22, 163, 74); // Green color
            doc.text(formatCurrency(slip.total_amount), 183, finalY, { align: 'right' });

            // --- Footer ---
            doc.setFontSize(8);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(150, 150, 150);
            doc.text("This is a computer-generated document. No signature is required.", 14, 280);
            doc.text("Nexus ERP System", 195, 280, { align: 'right' });

            doc.save(`Payslip_${monthStr.replace(' ', '_')}.pdf`);

        } catch (error) {
            console.error("Payslip Generation failed:", error);
        }
    };

    return (
        <DashboardLayout>
            <div className="space-y-8 pb-10">
                {/* Header */}
                <ScrollReveal width="100%">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                        <div>
                            <h1 className="text-3xl font-bold tracking-tight">Financial Overview</h1>
                            <p className="text-muted-foreground mt-1">Track your earnings, commissions, and payouts.</p>
                        </div>
                        <div className="flex gap-2">
                            <Button variant="outline" className="gap-2" onClick={handleDownloadReport}>
                                <Download className="h-4 w-4" /> Download Report
                            </Button>
                        </div>
                    </div>
                </ScrollReveal>

                {/* Stats Grid */}
                <ScrollReveal width="100%">
                    <div className="grid gap-6 md:grid-cols-3">
                        {/* Total Earnings Card */}
                        <Card className="bg-primary text-primary-foreground border-none shadow-lg relative overflow-hidden">
                            <div className="absolute right-0 top-0 h-32 w-32 bg-white/10 rounded-full blur-2xl -mr-10 -mt-10" />
                            <CardHeader className="pb-2 relative z-10">
                                <CardTitle className="text-primary-foreground/80 font-medium text-sm">Total Earnings (YTD)</CardTitle>
                            </CardHeader>
                            <CardContent className="relative z-10">
                                <div className="flex items-baseline gap-2">
                                    <span className="text-4xl font-bold">{formatCurrency(stats.totalEarnings)}</span>
                                </div>
                                <div className="mt-4 flex items-center gap-2 text-primary-foreground/70 text-sm">
                                    <TrendingUp className="h-4 w-4" />
                                    <span>+12% from last year</span>
                                </div>
                            </CardContent>
                        </Card>

                        {/* Details Card */}
                        <Card>
                            <CardHeader className="pb-2">
                                <CardTitle className="font-medium text-sm text-muted-foreground">Income Breakdown</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <div className="space-y-4">
                                    <div className="flex items-center justify-between">
                                        <div className="flex items-center gap-2">
                                            <div className="h-8 w-8 rounded-lg bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                                                <DollarSign className="h-4 w-4 text-blue-600 dark:text-blue-400" />
                                            </div>
                                            <div>
                                                <p className="text-sm font-medium">Base Salary</p>
                                                <p className="text-xs text-muted-foreground">Annual: {formatCurrency(stats.currentSalary)}</p>
                                            </div>
                                        </div>
                                        <span className="font-bold">{formatCurrency(stats.baseSalaryYTD)}</span>
                                    </div>
                                    <div className="flex items-center justify-between">
                                        <div className="flex items-center gap-2">
                                            <div className="h-8 w-8 rounded-lg bg-green-100 dark:bg-green-900/30 flex items-center justify-center">
                                                <TrendingUp className="h-4 w-4 text-green-600 dark:text-green-400" />
                                            </div>
                                            <div>
                                                <p className="text-sm font-medium">Commissions</p>
                                                <p className="text-xs text-muted-foreground">Performance</p>
                                            </div>
                                        </div>
                                        <span className="font-bold text-green-600">{formatCurrency(stats.commissionEarnedYTD)}</span>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>

                        {/* Pending Card */}
                        <Card className="border-l-4 border-l-yellow-500">
                            <CardHeader className="pb-2">
                                <CardTitle className="font-medium text-sm text-muted-foreground">Pending Payouts</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <div className="flex flex-col h-full justify-between">
                                    <div>
                                        <span className="text-3xl font-bold text-foreground">{formatCurrency(stats.commissionPending)}</span>
                                        <p className="text-sm text-muted-foreground mt-1">Expected to process by month end</p>
                                    </div>
                                    <div className="mt-4 pt-4 border-t flex items-center gap-2 text-yellow-600 dark:text-yellow-500 text-sm font-medium">
                                        <Clock className="h-4 w-4" />
                                        <span>{stats.commissionPendingCount || 0} deals processing</span>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </ScrollReveal>

                {/* Main Content Tabs */}
                <ScrollReveal width="100%">
                    <Tabs defaultValue="commissions" className="h-full space-y-6">
                        <div className="flex items-center justify-between">
                            <TabsList className="bg-white border w-full max-w-[400px] grid grid-cols-2">
                                <TabsTrigger value="commissions" className="h-9">Commissions</TabsTrigger>
                                <TabsTrigger value="payslips" className="h-9">Payslips</TabsTrigger>
                            </TabsList>
                        </div>

                        {/* Commissions Tab */}
                        <TabsContent value="commissions" className="space-y-4">
                            <Card>
                                <CardHeader>
                                    <CardTitle>Commission History</CardTitle>
                                    <CardDescription>
                                        Detailed log of all commissions earned from closed deals.
                                    </CardDescription>
                                </CardHeader>
                                <CardContent>
                                    {loading ? (
                                        <div className="py-8 text-center text-muted-foreground">Loading data...</div>
                                    ) : commissions.length === 0 ? (
                                        <div className="py-12 flex flex-col items-center justify-center text-center text-muted-foreground">
                                            <div className="bg-muted rounded-full p-4 mb-4">
                                                <DollarSign className="h-8 w-8 text-muted-foreground/50" />
                                            </div>
                                            <p className="text-lg font-medium text-foreground">No commissions yet</p>
                                            <p className="text-sm">Close more deals to start earning!</p>
                                        </div>
                                    ) : (
                                        <Table>
                                            <TableHeader>
                                                <TableRow>
                                                    <TableHead>Deal Name</TableHead>
                                                    <TableHead>Date</TableHead>
                                                    <TableHead>Status</TableHead>
                                                    <TableHead className="text-right">Amount</TableHead>
                                                </TableRow>
                                            </TableHeader>
                                            <TableBody>
                                                {commissions.map((item) => (
                                                    <TableRow key={item.id}>
                                                        <TableCell className="font-medium">
                                                            <div>
                                                                {item.deal_name}
                                                                <div className="text-xs text-muted-foreground hidden sm:block">Deal Value: {formatCurrency(item.leads?.value || 0)}</div>
                                                            </div>
                                                        </TableCell>
                                                        <TableCell>
                                                            <div className="flex items-center gap-2 text-muted-foreground">
                                                                <Calendar className="h-3 w-3" />
                                                                {new Date(item.date).toLocaleDateString()}
                                                            </div>
                                                        </TableCell>
                                                        <TableCell>
                                                            <Badge variant={
                                                                item.status === 'paid' ? 'success' :
                                                                    item.status === 'rejected' ? 'destructive' :
                                                                        'warning'
                                                            } className="capitalize shadow-none">
                                                                {item.status}
                                                            </Badge>
                                                        </TableCell>
                                                        <TableCell className="text-right font-bold text-success">
                                                            +{formatCurrency(item.amount)}
                                                        </TableCell>
                                                    </TableRow>
                                                ))}
                                            </TableBody>
                                        </Table>
                                    )}
                                </CardContent>
                            </Card>
                        </TabsContent>

                        {/* Payslips Tab */}
                        <TabsContent value="payslips" className="space-y-4">
                            <Card>
                                <CardHeader>
                                    <CardTitle>Payslips</CardTitle>
                                    <CardDescription>
                                        Monthly salary details and earnings statements.
                                    </CardDescription>
                                </CardHeader>
                                <CardContent>
                                    {loading ? (
                                        <div className="py-8 text-center text-muted-foreground">Loading data...</div>
                                    ) : payslips.length === 0 ? (
                                        <div className="py-12 flex flex-col items-center justify-center text-center text-muted-foreground">
                                            <div className="bg-muted rounded-full p-4 mb-4">
                                                <FileText className="h-8 w-8 text-muted-foreground/50" />
                                            </div>
                                            <p className="text-lg font-medium text-foreground">No payslips available</p>
                                            <p className="text-sm">Check back at the end of the month.</p>
                                        </div>
                                    ) : (
                                        <Table>
                                            <TableHeader>
                                                <TableRow>
                                                    <TableHead>Month</TableHead>
                                                    <TableHead>Base</TableHead>
                                                    <TableHead>Comm.</TableHead>
                                                    <TableHead>Status</TableHead>
                                                    <TableHead className="text-right">Total Net</TableHead>
                                                    <TableHead></TableHead>
                                                </TableRow>
                                            </TableHeader>
                                            <TableBody>
                                                {payslips.map((slip) => (
                                                    <TableRow key={slip.id}>
                                                        <TableCell className="font-medium">
                                                            {new Date(slip.month).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
                                                        </TableCell>
                                                        <TableCell>{formatCurrency(slip.base_amount)}</TableCell>
                                                        <TableCell className="text-green-600">+{formatCurrency(slip.commission_amount)}</TableCell>
                                                        <TableCell>
                                                            <Badge variant={slip.status === 'processed' || slip.status === 'paid' ? 'success' : 'secondary'} className="capitalize shadow-none">
                                                                {slip.status}
                                                            </Badge>
                                                        </TableCell>
                                                        <TableCell className="text-right font-bold">
                                                            {formatCurrency(slip.total_amount)}
                                                        </TableCell>
                                                        <TableCell className="text-right">
                                                            <Button
                                                                variant="ghost"
                                                                size="icon"
                                                                className="h-8 w-8"
                                                                onClick={() => handleDownloadPayslip(slip)}
                                                            >
                                                                <Download className="h-4 w-4 text-muted-foreground" />
                                                            </Button>
                                                        </TableCell>
                                                    </TableRow>
                                                ))}
                                            </TableBody>
                                        </Table>
                                    )}
                                </CardContent>
                            </Card>
                        </TabsContent>
                    </Tabs>
                </ScrollReveal>
            </div>
        </DashboardLayout>
    );
}
