import { useState } from "react";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { BarChart3, FileText, Download, Loader2, Calendar } from "lucide-react";
import { toast } from "sonner";
import { format } from "date-fns";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export function ReportsDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
    const [loading, setLoading] = useState(false);
    const [reportType, setReportType] = useState("revenue");

    const generatePDF = () => {
        const doc = new jsPDF();
        const dateStr = format(new Date(), 'MMM dd, yyyy');

        // --- Header Section ---
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.setFont("helvetica", "bold");
        doc.text("Nexus ERP", 14, 20);

        doc.setFontSize(14);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        const titleMap: Record<string, string> = {
            'revenue': 'Financial Performance Report',
            'inventory': 'Inventory Valuation & Stock Status',
            'employee': 'Employee Performance & Payroll'
        };
        doc.text(titleMap[reportType] || 'General Report', 14, 28);

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Date: ${dateStr}`, 14, 35);
        doc.text(`Report ID: REF-${Math.floor(Math.random() * 10000)}`, 14, 40);

        doc.setDrawColor(200, 200, 200);
        doc.line(14, 45, 196, 45);

        // --- Content Section (Mock Data) ---
        let head: any[] = [];
        let body: any[] = [];

        if (reportType === 'revenue') {
            head = [['Source', 'Transactions', 'Revenue', 'Growth']];
            body = [
                ['Product Sales', '1,234', '$125,000.00', '+12%'],
                ['Services', '85', '$42,500.00', '+5%'],
                ['Subscriptions', '543', '$28,200.00', '+8%'],
                ['Licensing', '12', '$15,000.00', '+2%'],
                ['Refunds', '23', '-$1,200.00', '-1%'],
                ['', 'Total', '$209,500.00', '+26%']
            ];
        } else if (reportType === 'inventory') {
            head = [['SKU', 'Product Name', 'Category', 'Stock', 'Value']];
            body = [
                ['PROD-001', 'Wireless Mouse', 'Electronics', '150', '$4,500'],
                ['PROD-002', 'Mechanical Keyboard', 'Electronics', '45', '$8,100'],
                ['PROD-003', 'Office Chair', 'Furniture', '12', '$3,600'],
                ['PROD-004', 'Monitor Stand', 'Accessories', '89', '$2,670'],
                ['PROD-005', 'USB-C Cable', 'Accessories', '300', '$1,500'],
            ];
        } else if (reportType === 'employee') {
            head = [['Employee', 'Department', 'Role', 'Attendance', 'Performance']];
            body = [
                ['John Doe', 'Engineering', 'Senior dev', '98%', 'Excellent'],
                ['Jane Smith', 'Sales', 'Lead', '95%', 'Good'],
                ['Mike Johnson', 'Support', 'Agent', '92%', 'Average'],
                ['Sarah Williams', 'HR', 'Manager', '99%', 'Excellent'],
            ];
        }

        autoTable(doc, {
            startY: 50,
            head: head,
            body: body,
            theme: 'grid',
            headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 3 },
            alternateRowStyles: { fillColor: [248, 250, 252] },
        });

        // --- Footer Section ---
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
            doc.text(`Generated by Nexus ERP System - Confidential`, 14, pageHeight - 10);
            doc.text(`Page ${i} of ${pageCount}`, pageSize.width - 25, pageHeight - 10);
        }

        doc.save(`Nexus_Report_${reportType}_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
    };

    const handleDownload = () => {
        setLoading(true);
        try {
            generatePDF();
            toast.success("Report generated successfully", {
                description: "Your PDF download has started."
            });
            setTimeout(() => {
                onOpenChange(false); // Close dialog
                setLoading(false);
            }, 500);
        } catch (error: any) {
            console.error("PDF Generation Error", error);
            toast.error("Failed to generate PDF", {
                description: error.message || "Unknown error occurred"
            });
            setLoading(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-md border-0 shadow-2xl p-0 gap-0 overflow-hidden rounded-xl">
                <div className="relative bg-gradient-to-br from-indigo-900 to-indigo-700 px-6 py-6 text-white overflow-hidden shrink-0">
                    <div className="absolute top-0 right-0 -mt-4 -mr-4 h-24 w-24 rounded-full bg-white/10 blur-xl"></div>
                    <div className="absolute bottom-0 left-0 -mb-4 -ml-4 h-20 w-20 rounded-full bg-black/20 blur-xl"></div>
                    <DialogHeader className="relative z-10">
                        <DialogTitle className="text-xl font-bold flex items-center gap-2">
                            <FileText className="h-5 w-5" /> Export Reports
                        </DialogTitle>
                        <DialogDescription className="text-indigo-100/80">
                            Select a report type to generate detailed analytics.
                        </DialogDescription>
                    </DialogHeader>
                </div>

                <div className="p-6 bg-background space-y-6">
                    <RadioGroup defaultValue="revenue" onValueChange={setReportType} className="grid grid-cols-1 gap-4">
                        <div className={`flex items-center space-x-4 rounded-xl border p-4 transition-all cursor-pointer ${reportType === 'revenue' ? 'border-indigo-600 bg-indigo-50/50 ring-1 ring-indigo-600/20' : 'border-slate-200 hover:bg-slate-50'}`}>
                            <RadioGroupItem value="revenue" id="revenue" className="border-indigo-600 text-indigo-600" />
                            <Label htmlFor="revenue" className="flex-1 cursor-pointer">
                                <span className="font-semibold text-foreground block">Revenue & Sales</span>
                                <span className="text-xs text-muted-foreground">Detailed breakdown of income sources and trends.</span>
                            </Label>
                            <BarChart3 className={`h-5 w-5 ${reportType === 'revenue' ? 'text-indigo-600' : 'text-slate-400'}`} />
                        </div>

                        <div className={`flex items-center space-x-4 rounded-xl border p-4 transition-all cursor-pointer ${reportType === 'inventory' ? 'border-indigo-600 bg-indigo-50/50 ring-1 ring-indigo-600/20' : 'border-slate-200 hover:bg-slate-50'}`}>
                            <RadioGroupItem value="inventory" id="inventory" className="border-indigo-600 text-indigo-600" />
                            <Label htmlFor="inventory" className="flex-1 cursor-pointer">
                                <span className="font-semibold text-foreground block">Inventory Valuation</span>
                                <span className="text-xs text-muted-foreground">Current stock levels, low stock alerts, and value.</span>
                            </Label>
                            <FileText className={`h-5 w-5 ${reportType === 'inventory' ? 'text-indigo-600' : 'text-slate-400'}`} />
                        </div>

                        <div className={`flex items-center space-x-4 rounded-xl border p-4 transition-all cursor-pointer ${reportType === 'employee' ? 'border-indigo-600 bg-indigo-50/50 ring-1 ring-indigo-600/20' : 'border-slate-200 hover:bg-slate-50'}`}>
                            <RadioGroupItem value="employee" id="employee" className="border-indigo-600 text-indigo-600" />
                            <Label htmlFor="employee" className="flex-1 cursor-pointer">
                                <span className="font-semibold text-foreground block">Employee Performance</span>
                                <span className="text-xs text-muted-foreground">Sales targets, attendance, and commission data.</span>
                            </Label>
                            <Calendar className={`h-5 w-5 ${reportType === 'employee' ? 'text-indigo-600' : 'text-slate-400'}`} />
                        </div>
                    </RadioGroup>
                </div>

                <DialogFooter className="p-6 pt-0 bg-background">
                    <Button variant="outline" onClick={() => onOpenChange(false)} className="mr-2">Cancel</Button>
                    <Button onClick={handleDownload} disabled={loading} className="bg-indigo-600 hover:bg-indigo-700 text-white shadow-lg shadow-indigo-200">
                        {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
                        Download PDF
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
